version: "3"
services:
  app:
    # replace username/repo:tag with your name and image details
    image: jxl212/pogobot:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
